### ISSUE TITLE
Not running in Karma tests

### ISSUE THREAD

**Issue by goncalomarques** [AlmogBaku/ngFacebook#44]
I'm using the daftmonk angular-fullstack generator and although I have included the ngFacebook lib/angular-facebook.js file, I get the error Module 'ngFacebook' is not available! 

I have triple checked the file paths by now and set karma logLevel to LOG_DEBUG and confirmed that the file is being served.

**Comment by AlmogBaku** [comment]
Can you please give an example on plunker?
It sounds like a bug in your project.. nothing generic.

**Comment by AlmogBaku** [comment]
@goncalomarques can you update us?

Also notice that we have no karma tests, but phrotractor+cucumber tests

**Comment by goncalomarques** [comment]
I'm sorry I've failed to update this. It turns out it was my fault - I solved it creating a dedicated run block file for the ngFacebook initial configs and excluded it in my karma tests config.

Tomorrow I'll check on what was causing this as I forgot it by now but you can mark it as closed.

Thank you very much and my apologies

**Comment by AlmogBaku** [comment]
Can you contribute these tests?

**Comment by goncalomarques** [comment]
I think you misunderstood me - these tests are for my project. They are not tests to your component
